services:

  # development container
  development:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DB=${DATABASE_DB}
      - DATABASE_PORT=${DATABASE_PORT}
    volumes:
      - ..:/workspace
    stdin_open: true
    network_mode: "host"   
  # database
  mysql_db:
    hostname: mysql_db
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_DB}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports: 
      - 127.0.0.1:${DATABASE_PORT}:3306
